# Generated by Django 4.2.3 on 2023-07-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optional_phone_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Magaza ',
                'verbose_name_plural': 'Magazalar ',
            },
        ),
    ]
