# Generated by Django 4.2.3 on 2023-07-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': ' Magaza ', 'verbose_name_plural': ' Magazalar '},
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
