# Generated by Django 4.2.3 on 2023-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_store_optional_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='footer_description',
            field=models.TextField(null=True, verbose_name='footer-deki metn'),
        ),
    ]
