# Generated by Django 4.2.3 on 2023-07-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productimage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
