# Generated by Django 4.2.3 on 2023-08-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_mainorder_orderitem_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainorder',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
